# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Tianpu Zhang
title: Master Student at North China University of Technology
email: zhangtianpu@hotmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: facespics
github_username:  zhangtianpu
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: channel/UCLJCBZGxg6-9aGidpYI5FtQ
# googleplus_username: +jekyll
orcid_username: 0000-0002-7146-8829

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/Treking.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Tianpu Zhang and I'm a post-graduate student at the North China University of Technology, majoring in **computer technology**.  As well as, I obtained **3.91 GPA** through my hard work. 
  At the same time, at 2021 and 2022, I was rewarded the **first calss academic scholarship** for post-graduate students and the **national scholarship** for post-graduate students.
  During these years, my research insterests are **deep learning**, **spatio-temporal big data** and **smart city**. 
  In the process of research, I gradually proficiency with some technology in deep learing, big data and so on, while I published some papers you can find it at the Publications section.



content:
  - title: Education
    layout: list
    content:
      - layout: left
        border: weak
        title: The North China University of Technology
        sub_title: Information Science and Technology
        caption: September 2020 - Present
        description: |
          I am a postgraduate student right now in the School of Information Science and Technology at North China University of Technology. 
          I will graduate by June 2023 and get my master of engineering degree. The laboratory I worked for is **Beijing Key Laboratory on Integration and Analysis of Large-scale Stream Data** and the head of it is **Yanbo Han professor**.
          My major professor is **Weilong Ding**, under his guidiance, I have researched and achieved some publications on deep learning, spatio-temporal big data and smart city. 
          My **major courses** include Machine learning and applications, Mathematical Foundations in Deep Learning, Advanced Algorithm Design and Analysis, Advanced Mathematical Statistics, Matrix Analysis and so on.
      - layout: left
        border: weak
        title: Beijing University of Civil Engineering and Architecture
        sub_title: Geomatics and Urban Spatial Informatics
        caption: September 2015 - June 2017
        description: |
          My bachelor's degree is in **geographic infomation science** in the School of Geomatics and Urban Spatial Informatics at Beijing University of Civil Engineering and Architecture.
          My **major courses** have Embedded development of GIS, GIS Software Application, Computational Method, Spatial Database, Photogrammetry Fundamental, Technology of Satellite navigation and positioning, Application of ENVI, Principles and Applications of Remote Sensing and so on. 
          In the course of my studies, I was intorducted to programming and developed a keen interest in it. Therefore, I chosen a graduation project related programming named **The Development of Lightweight WebGis Based on Json**, which used geoserver and opeenlayers to display geographic information and applied ECharts to show statistical data.

  - title: Publications
    layout: list
    content:
      - layout: top-middle
        border: weak
        description: |
          **Zhang, T.**, Ding, W., Chen, T., Wang, Z., & Chen, J. (2021). A graph convolutional method for traffic flow prediction in highway network. Wireless Communications and Mobile Computing,2021. 
          
          In this paper, we propose a graph convolutional method. And the name of our model proposed is the hybrid graph convolutional network (HGCN), which comprehensively considers time, space, weather conditions and date type to achieve better predicted results of traffic flow at highway stations. 
          
          **Zhang, T.**, Ding, W., Xing, M., Chen, J., Du, Y., & Liang, Y. (2021, October). Geographic and Temporal Deep Learning Method for Traffic Flow Prediction in Highway Network. In International Conference on Collaborative Computing: Networking, Applications and Worksharing (pp. 385-400). Springer, Cham.
          
           In this paper a method is proposed based on deep learning that can capture the geographic spatial relationship among toll stations, the dynamic temporal relationship of historical traffic flow, extreme weather and calendar types. On the three metrics of MAPE, MAE, and RMSE, the prediction effect of our model has increased by 30% compared with KNN, GBRT and LSTM models.
          
          Xing, M., Ding, W., Li, H., & **Zhang, T**. (2022). A Power Transformer Fault Prediction Method through Temporal Convolutional Network on Dissolved Gas Chromatography Data. Security and Communication Networks, 2022.
        
          We propose a method for fault prediction for power transformers based on dissolved gas chromatography data: after data preprocessing of defective raw data, fault classification is performed based on the predictive regression results. Here, Mish-SN Temporal Convolutional Network (MSTCN) is introduced to improve the accuracy during the regression step. Several experiments are conducted using data set from China State Grid. The discussion of the results of experiments is provided.
        
  - title: In Submissions
    layout: list
    content:
      - layout: top-middle
        border: weak
        description: |
           Ding, W, **Zhang, T.**,  Xing, M.,  Attention-based Dynamic Graph Convolutional Recurrent Neural Network for Traffic Flow Prediction in Highway Transportation. The Web Conference 2023: International World Wide Web Conference (WWW), 2023.
           
           In this paper, a novel Attention-based Dynamic Graph Convolutional Recurrent Neural Network (ADGCRNN) is proposed to improve traffic flow prediction. Through a dedicated self-attention mechanism, 
           the characteristics of different temporal resolutions can be extracted from a global perspective. 
           Then, dynamically generated graphs in various semantics are fused with the static physical graph of road network, which would fully exploit spatial characteristics. 
           For those dynamic graphs, another gated kernel is introduced further to avoid information overload and focus on local convolution. 
           Experiments on two public datasets, PeMSD4 and PeMSD8, show that our work yields more accurate predictive results than current state-of-the-art.
            
  - title: Project Experiience
    layout: list
    content:
      - layout: left
        border: weak
        title: Yunqishidai Technology Co.
        sub_title: Data Analysis Engineer
        caption: July 2019 - August 2020        
        description: |
          As a third-party vendor, it works for the state grid to provide technical support to the development state grid new energy cloud platform. 
          My duty was to build data storage and analysis platform through big data technology to support the state grid new energy cloud platform which is a system facilitating citizens’ electricity transactions. 
          Meanwhile, an electricity power predictive system for photovoltaic power stations and a recommendation system for news in the renewable energy field was designed by using machine learning technology. 
          
      - layout: left
        border: weak
        title: Unicom big data Co., Ltd
        sub_title: Data Analysis Engineer
        caption: November 2018 - March 2019
        description: |
          As one of the three major telecom operators in China, Unicom Big Data has petabytes of data.
          My main work was to use big data technologies such as hive, spark, etc. to analyze the custom’s behavior to build data profile and extract relevant data from data warehouse according to customer needs.
          
#   - title: Project Experiience
#     layout: text
#     content: | # this will include new lines to allow paragraphs
#       Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#       - Rock climbing
#       - Gaming
#       - Knitting
#       - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#       Look at this cool image  
#       ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
